### ISSUE TITLE
Relative path cannot be resolved when called from outside this module

### ISSUE THREAD

**Issue by dgrstl** [hashicorp/terraform-aws-consul#10]
https://github.com/hashicorp/terraform-aws-consul/blob/eb04a460a393763c38a55774077edaaafa755e6f/modules/consul-cluster/main.tf#L123

For example, https://github.com/hashicorp/terraform-aws-nomad/blob/master/examples/nomad-consul-separate-cluster/main.tf#L123-L124

**Comment by dgrstl** [comment]
Ditto for https://github.com/hashicorp/terraform-aws-consul/blob/master/modules/consul-cluster/main.tf#L185

**Comment by brikis98** [comment]
Are you on Terraform 0.10.6? If so, this is a bug in Terraform as reported in https://github.com/hashicorp/terraform-aws-vault/issues/6.

**Comment by dgrstl** [comment]
I am, tested with 0.10.5 and works fine.

**Comment by brikis98** [comment]
OK, great. I'm going to close this one in favor of https://github.com/hashicorp/terraform-aws-vault/issues/6. Hopefully, the next release of Terraform will fix this for good.
