### ISSUE TITLE
Release new version in public registry?

### ISSUE THREAD

**Issue by estein9825** [hashicorp/terraform-aws-consul#105]
Currently tag 0.4.4 is the only option in the public registry but it doesn't align with this GitHub master. When will you guys release a new version into the public registry?

**Comment by brikis98** [comment]
@Etiene Could you create a new release?

**Comment by brikis98** [comment]
Thx for the heads up @estein9825!

**Comment by estein9825** [comment]
Also, I just tested it and it seems the instance_profile logic always results in an empty value returned.

**Comment by brikis98** [comment]
We've had many releases since this issue was filed, and I can see them in the registry. Closing.
