### ISSUE TITLE
Need IAM Policy Name not ARN/ID

### ISSUE THREAD

**Issue by estein9825** [hashicorp/terraform-aws-consul#106]
Terraform doesn't allow iam role lookups by ID or ARN, so it doesn't help much that you guys return that info, especially given you're doing name_prefix and not name in your call.

**Comment by brikis98** [comment]
Sounds like a good addition. Would you be up for a really quick PR?

**Comment by tomaspinho** [comment]
Need this, opened PR.

**Comment by brikis98** [comment]
Update: it's a bit confusing, but in Terraform, the `id` output of `aws_iam_role` is the same as `name`.  So between `id` and `arn` outputs, you should have everything you need.
