### ISSUE TITLE
t2.micro instance type

### ISSUE THREAD

**Issue by devvesa** [hashicorp/terraform-aws-consul#116]
[Consul Reference architecture](https://learn.hashicorp.com/consul/advanced/day-1-operations/reference-architecture#consul-servers) recommends to use either a `m5.large` or a `m5.xlarge` instance type for production deployments in AWS, and also recommends to avoid "Burstable CPU" instance types (the T family).

However, the consul module uses a hard coded `t2.micro` instance type for the autoscaling group. Is there any reason for that? May you accept a PR to parametrise this value? (I want to avoid use our own fork as much as possible).

**Comment by brikis98** [comment]
Please note that while the modules in the `/modules` folder are meant for production use, the code in the root of this repo is *example* code designed for learning and ease-of-deployment. The modules in the `/modules` folder allow you to configure the instance type as you want.

I've also filed https://github.com/hashicorp/terraform-aws-consul/pull/118 to try to clarify this more.

**Comment by devvesa** [comment]
Gotcha @brikis98 ! thanks for the quick answer.
