### ISSUE TITLE
consul_cluster module subnet_ids and availability_zones is incorrect

### ISSUE THREAD

**Issue by iainthegray** [hashicorp/terraform-aws-consul#126]
The docs state that "At least one of var.subnet_ids or var.availability_zones must be non-empty."

If you run the module with availability_zones set then it fails as it tries to add ec2 to incorrect subnets.
In my setup I have the default VPC and a new VPC. If I do not specifically state the subnet_ids then the module will try and put the EC2 in the incorrect VPC.

**Comment by brikis98** [comment]
Hm, shouldn't the `aws_autoscaling_group` resource use the default VPC if you don't specify one explicitly?

**Comment by brikis98** [comment]
No response for a long time. Closing.
