### ISSUE TITLE
Support for Ubuntu 18.04 

### ISSUE THREAD

**Issue by sharmaanshul21** [hashicorp/terraform-aws-consul#141]
Is there any plan, in nearby future to support Ubuntu 18.04? If not, I am happy to work on AWS related modules to add support for 18.04 if it is OK with you guys. I can start with the Consul, but yes definitely need help/pointers from you guys. 

@Etiene @brikis98

**Comment by brikis98** [comment]
Yes, 18.04 is on our roadmap. @yorinasub17 Can comment on rough timeline.

**Comment by sharmaanshul2102** [comment]
Cool, if you guys haven't started 18.04, I can look into it.

**Comment by yorinasub17** [comment]
Hi @sharmaanshul2102 , we haven't started this yet, and most likely won't get to it until after the tf12 update is done. So would really appreciate a PR for it!

I will suggest starting by updating the packer build to add a new builder for ubuntu 18.04 (https://github.com/hashicorp/terraform-aws-consul/blob/master/examples/consul-ami/consul.json), and then adding a Ubuntu1804 test to the main consul-cluster test (https://github.com/hashicorp/terraform-aws-consul/blob/master/test/consul_cluster_test.go) that you can iterate on.
