### ISSUE TITLE
Allow client_addr to be passed in as a param to run-consul

### ISSUE THREAD

**Issue by schledererj** [hashicorp/terraform-aws-consul#147]
Currently, the config file that the run-consul script generates has the `client_addr` hard-coded to 0.0.0.0. I would like to set my `client_addr` to 127.0.0.1 to restrict access to the UI to localhost only (and have an nginx reverse proxy running on the same host that can handle authentication and presenting a client certificate). Can we update the script to have a `--client-addr` param that defaults to 0.0.0.0?

**Comment by brikis98** [comment]
Could you [override the generated config](https://github.com/hashicorp/terraform-aws-consul/tree/master/modules/run-consul#overriding-the-configuration)?

**Comment by schledererj** [comment]
Ah, looks like I missed that in the documentation :/ We'll just do that. Thanks!
