### ISSUE TITLE
variable reference is not correct - special characters omitted

### ISSUE THREAD

**Issue by debojitkakoti** [hashicorp/terraform-aws-consul#150]
I can see all the special characters is being trimmed in the code.
https://github.com/hashicorp/terraform-aws-consul/blob/master/modules/consul-cluster/main.tf

For example the following line
 ` service_linked_role_arn   = var.service_linked_role_arn`

It should be
  service_linked_role_arn   = "${var.service_linked_role_arn}"

**Comment by Etiene** [comment]
Since version 0.7.0 this module has been updated to be compatible with Terraform version 0.12.0 and up, which means that these special characters are no longer necessary. If you are using an older version of terraform, you should use version 0.6.1 or lower of this module.
