### ISSUE TITLE
Support arbitrary tags

### ISSUE THREAD

**Issue by leoblanc** [hashicorp/terraform-aws-consul#162]
Hello, we want to add arbitrary tags to the resources created by the root module. 

Our use case is that AWS resources not properly tagged are automatically deleted by an internal tool. 

It seems like it's not possible to configure tags in [variables.tf](https://github.com/hashicorp/terraform-aws-consul/blob/master/variables.tf)

Actually, it seems like tags are [hardcoded here](https://github.com/hashicorp/terraform-aws-consul/blob/master/main.tf#L85).

Can you please add such support please?

Thank you very much!

**Comment by brikis98** [comment]
As explained in the docs, the code in the root of this repo is an *example* of how to use the modules in the `modules` folder. This example is designed to make it easy to experiment with the code, but not production use. If you want to use the code for product, follow the code in the example to create your own module that uses the code in the `modules` folder directly. The code in the `modules` folder allows you to set whatever tags you need: https://github.com/hashicorp/terraform-aws-consul/blob/master/modules/consul-cluster/variables.tf#L239
