### ISSUE TITLE
consul.json using old packer var 

### ISSUE THREAD

**Issue by punkrokk** [hashicorp/terraform-aws-consul#170]
`clean_ami_name1 has been replaced by `clean_resource_name` in  packer v1.4. Updated `consul.json` to reflect this. 

Ref: https://github.com/hashicorp/packer/pull/7456

The current consul.json template needs this update. 

It might also make sense to update the readme for the consul template to provide a note about needing a `vpc_id` and/or `subnet_id` in order for the packer build to run. 

Let me know.

**Comment by brikis98** [comment]
Thx for the PR in #169!

The Packer template should, by default, use the Default VPC. `vpc_id` and `subnet_id` are only required if you don't have a default VPC.

**Comment by punkrokk** [comment]
@brikis98 Makes Sense. I think PR #169 is ready to go then.
