### ISSUE TITLE
Feature Request: Add Server and Client IP addresses to output

### ISSUE THREAD

**Issue by schristoff** [hashicorp/terraform-aws-consul#180]
Howdy, 
It would be super handy if this module could output the external IP addresses assigned to server and clients. I see there is some scripting made to do this in either `test` or `examples` 
Is there any reason this isn't done currently? 

Thanks! :)

**Comment by brikis98** [comment]
The Consul nodes run in an Auto Scaling Group (ASG). Terraform does not provide the IP address outputs for an ASG, as the ASGs are dynamic by design, and new instances can come and go any time.
