### ISSUE TITLE
Consul cluster on spot instances

### ISSUE THREAD

**Issue by igoris** [hashicorp/terraform-aws-consul#211]
I'm trying to understand what's the correct way to run consul_cluster with spot_price specified. It seems to me that as all spot requests will be created with the same price, all spot instances may go down at the same time if current price exceeds the spot_price. This will require manual intervention to restore state from backups and at least some data loss. The best idea I have so far is to run N/2+1 instances as on-demand and remaining as spot. Is this how it's intended to be used or am I missing something?
Thanks and sorry if this is not the correct place for this type of questions.

**Comment by brikis98** [comment]
Sorry for the delay; we've been super buried. This sort of question is probably best for the Consul community forum: https://discuss.hashicorp.com/c/consul/29.
