### ISSUE TITLE
Links to consul cluster example are broken in docs

### ISSUE THREAD

**Issue by bizmate** [hashicorp/terraform-aws-consul#23]
When reading the documentation there is a broken link for the fully working cluster example
https://github.com/hashicorp/terraform-aws-consul/blame/master/modules/consul-cluster/README.md#L58

The link at the moment is https://github.com/hashicorp/terraform-aws-consul/tree/master/MAIN.md and it is a 404

As it is the first time I am using this module could you please confirm the right link? Is the root-example the only one available?

**Comment by brikis98** [comment]
Ah, good catch. I fixed the link: https://github.com/hashicorp/terraform-aws-consul/commit/933be2fae342099f58575a1fa24f1a8e4f42bad0. 

The root example is the main example available.

**Comment by bizmate** [comment]
@brikis98 thank you

**Comment by bizmate** [comment]
I dont want to sound too pedantic but arent we supposed to use this as a terraform module instead of git cloning the repo? see https://github.com/hashicorp/terraform-aws-consul/blame/master/examples/root-example/README.md#L25 I will open a separate issue if ok.

**Comment by brikis98** [comment]
Ah, yea. Terraform added ability to use Registry URLs directly from Terraform after we built these modules, so it's definitely worth updating the docs accordingly. PR welcome!
