### ISSUE TITLE
Consul AMI example - missing Git for AWS example

### ISSUE THREAD

**Issue by davidham** [hashicorp/terraform-aws-consul#30]
I was trying to set up the AMI for production usage per your [example code on this page](https://github.com/hashicorp/terraform-aws-consul/tree/master/examples/consul-ami). The Amazon Linux version failed with this error:

`amazon-linux-ami: /tmp/script_7892.sh: line 2: git: command not found`

I was able to re-run the Amazon Linux one by modifying the `inline` block as follows:

```
"inline": [
      "sudo yum install -y git",
      "git clone --branch v0.1.0 https://github.com/hashicorp/terraform-aws-consul.git /tmp/terraform-aws-consul",
      "/tmp/terraform-aws-consul/modules/install-consul/install-consul --version {{user `consul_version`}}",
      "/tmp/terraform-aws-consul/modules/install-dnsmasq/install-dnsmasq"
    ],
```

**Comment by brikis98** [comment]
Ah, good point. Ubuntu has git installed by default, but Amazon Linux does not. A PR to improve those docs would be welcome!

**Comment by jasonmcintosh** [comment]
Would you consider this fixed with the dependency list documented?

**Comment by brikis98** [comment]
The example AMI readme now documents this. Thx @jasonmcintosh.
