### ISSUE TITLE
aws provider authentication issue

### ISSUE THREAD

**Issue by kinpa3a** [hashicorp/terraform-aws-consul#39]
# Version info 
* module.consul = "0.1.0"
* provider.aws: version = "~> 1.7"
* provider.template: version = "~> 1.0"

# Situation
I read this article : https://www.terraform.io/intro/getting-started/modules.html

I wrote `example.tf` :
```
provider "aws" {
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
  region     = "${var.region}”
}

module "consul" {
    source = "hashicorp/consul/aws"
    aws_region = "${var.region}"
    num_servers = "3"
}
```

When I run `terraform plan` I got the message below.

```
data.template_file.user_data_client: Refreshing state...
data.template_file.user_data_server: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* module.consul.provider.aws: No valid credential sources found for AWS Provider.
  Please see https://terraform.io/docs/providers/aws/index.html for more information on
  providing credentials for the AWS Provider
```

After researching I tried to modify `example.tf` :

```
provider "aws" {
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
  region     = "${var.region}”
}

module "consul" {
    source = "hashicorp/consul/aws"

    providers = {
        aws = "aws"
    }
    aws_region = "${var.region}"
    num_servers = "3"
}
```

and it works.

# Question 
Is some configuration changed and do I have to specify the "provider"?
Or did I do something wrong?

Thanks. :-)

**Comment by brikis98** [comment]
Sorry for the confusion. The Terraform Registry requires that you have a "module" at the root of your repo that can be deployed. For complicated infrastructure like Consul, this "module" is actually just example code, and it already defines a `provider` block: https://github.com/hashicorp/terraform-aws-consul/blob/master/main.tf#L9-L11. 

So the recommended usage pattern is to copy this root example and customize it to your needs.

**Comment by brikis98** [comment]
@KFishner: see above for another issue with the root sometimes containing a "module" and sometimes containing an "example."

**Comment by kinpa3a** [comment]
Oh thanks. I understand why it worked and why you did. :-)
Thank you for the prompt reply.
