### ISSUE TITLE
RFE: Support TLS/Encrypt options

### ISSUE THREAD

**Issue by jasonmcintosh** [hashicorp/terraform-aws-consul#41]
Opening this as a reference - I plan on working to add this at some point, as we're wanting this when using it for Vault purposes.  

Documentation:
https://www.consul.io/docs/agent/encryption.html

Note there WOULD be a challenge if someone attempted to use this on an existing cluster that did NOT have encryption appropriately enabled, but that's a separate discussion.

Places that need to be modified:
Config file:
https://github.com/hashicorp/terraform-aws-consul/blob/master/modules/run-consul/run-consul#L194
User data files to pass it to run-consul
https://github.com/hashicorp/terraform-aws-consul/tree/master/examples/root-example
Finally the below to add variables for the user data scripts
https://github.com/hashicorp/terraform-aws-consul/blob/master/main.tf#L92

Might be missing things... but it's a start

**Comment by brikis98** [comment]
Does this cover what you're looking for? https://github.com/hashicorp/terraform-aws-consul/tree/master/modules/run-consul#how-do-you-handle-encryption

**Comment by jasonmcintosh** [comment]
Exactly :)  The vault module has support for these on AWS - be nice to add it here.  Figure I'll work on that a bit here when I get some spare time - doesn't look like it'll be too hard to add support for it.

**Comment by patoarvizu** [comment]
I'll be submitting a PR for this shortly...

**Comment by patoarvizu** [comment]
I'd appreciate any feedback on the PR above :)

**Comment by brikis98** [comment]
Fixed in #58.
