### ISSUE TITLE
Installation Doesn't work

### ISSUE THREAD

**Issue by satssin** [hashicorp/terraform-aws-consul#43]
This consul installation doesn't work on Centos7, supervisorD doesn't start after the installation.
 Supoervisord init script isn't compatible with centos.. the place that it appears to break down is the fact that on centos7, pip installs supervisord binary to /usr/bin/supervisord as well as supervisorctl but the init script in that package (  https://github.com/hashicorp/terraform-aws-consul/blob/master/modules/install-consul/supervisor-init... ) expects them in /usr/local/bin

**Comment by brikis98** [comment]
I believe this very issue was fixed in #40. Try the newest version!
