### ISSUE TITLE
Add option to set -domain in run-consul

### ISSUE THREAD

**Issue by george24601** [hashicorp/terraform-aws-consul#54]
Thanks a lot for these examples/modules! They saved me a great deal of time!

Context:
We put our internal services under private-subdomain.public-domain.com, and use consul as the internal DNS. 

Suggestion:
It would be great if we could add the support for "-domain" config in run-consul.  I had to fork the repo and modify the script myself.

**Comment by brikis98** [comment]
No need to fork. You can specify custom configs as documented here: https://github.com/hashicorp/terraform-aws-consul/tree/master/modules/run-consul#overriding-the-configuration
