### ISSUE TITLE
`run-consul` fails to lookup tags for instance

### ISSUE THREAD

**Issue by karma0** [hashicorp/terraform-aws-consul#63]
In attempting to run a consul cluster, I'm receiving the following output from the user-data script that calls `run-consul`:

```
HTTPSConnectionPool(host='ec2.us-east-1.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f67b5423278>, 'Connection to ec2.us-east-1.amazonaws.com timed out. (connect timeout=60)'))
2018-04-24 22:24:11 [WARN] [run-consul] This Instance i-09318afe7d984d50f in us-east-1 does not have any Tags.
2018-04-24 22:24:11 [WARN] [run-consul] Will sleep for 10 seconds and try again.
```

Executing `run-consul` by hand reveals that it will consistently hang and timeout while trying to contact `ec2.us-east-1.amazonaws.com`.  I am running the instances on a few private VPC subnets that can communicate with one another, but are relatively locked down otherwise.

Are the tags necessary?  If so, what do I need to do to configure `terraform` to allow access to `ec2.us-east-1.amazonaws.com`?  Finally, are there other services/hosts that `run-consul` needs access to from these VPC/subnets?

**Comment by brikis98** [comment]
> I am running the instances on a few private VPC subnets that can communicate with one another, but are relatively locked down otherwise.

Do you allow outbound Internet access? If not, then `run-consul` won't be able to talk to the AWS APIs to find and connect to the other Consul servers.

**Comment by karma0** [comment]
Added a NAT gateway, and that seemed to resolve the connection issue.  Now I'm getting the following:

```
2018-04-25 23:52:20 [INFO] [run-consul] Looking up tags for Instance i-021d2c40784a70355 in us-east-1

An error occurred (UnauthorizedOperation) when calling the DescribeTags operation: You are not authorized to perform this operation.
2018-04-25 23:52:20 [WARN] [run-consul] This Instance i-021d2c40784a70355 in us-east-1 does not have any Tags.
2018-04-25 23:52:20 [WARN] [run-consul] Will sleep for 10 seconds and try again.

```

**Comment by brikis98** [comment]
Could you check if that Instance has tags? If not, are you running it with the `consul-cluster` module or some other way?

**Comment by karma0** [comment]
It is `consul-cluster`.  Well, technically I'm trying to run a `vault-cluster` and `nomad-cluster`, and I've integrated `run-consul` into the mix, executing similarly to how `consul-cluster` executes.  In answer to your question, there are tags on the servers.

You can see what working on [here](https://github.com/TheLarsonAgency/koralamode) on the `master` branch.  The README is incomplete, so you may need to skip that part of it.

**Comment by brikis98** [comment]
Oh, sorry, I missed the obvious error message:

```
An error occurred (UnauthorizedOperation) when calling the DescribeTags operation: You are not authorized to perform this operation.
```

To look up tags, your servers need an IAM role with the `DescribeTags` IAM permission. That's created by the [consul-iam-policies module](https://github.com/hashicorp/terraform-aws-consul/blob/master/modules/consul-iam-policies/main.tf) which is added here in the `consul-cluster` module: https://github.com/hashicorp/terraform-aws-consul/blob/master/modules/consul-cluster/main.tf#L202-L206. 

Did you change anything about the IAM role or policies?

**Comment by karma0** [comment]
That worked! My setup was hacked together a bit so that there's some overlap in services with `nomad-cluster` and `vault-cluster`, and I'm using a single AMI, but adding iam_policies for both of my clusters resolved the issue!
