### ISSUE TITLE
Need to add tags to taggable resources

### ISSUE THREAD

**Issue by jcejohnson** [hashicorp/terraform-aws-consul#72]
Similar to my recent [terraform-aws-vault PR](https://github.com/hashicorp/terraform-aws-vault/pull/81), I have a need to apply tags to all taggable resources (corporate policy). I have a [commit](https://github.com/EFXCIA/terraform-aws-consul/commit/c74baade3703fcb8f0989b844cfd0d3bd0bf70ce) on our fork and will be submitting a PR as soon as I test it in our environment.

**Comment by brikis98** [comment]
Sounds good!

**Comment by jcejohnson** [comment]
https://github.com/hashicorp/terraform-aws-consul/pull/74
