### ISSUE TITLE
Ability to specify VPC

### ISSUE THREAD

**Issue by andrewmeissner** [hashicorp/terraform-aws-consul#8]
As a feature request, could the ability specify which VPC the resources are stood up in be added?  Right now it only uses the default VPC.

Thanks!

**Comment by brikis98** [comment]
The underlying submodules already support this: e.g., [vpc_id](https://github.com/hashicorp/terraform-aws-consul/blob/master/modules/consul-cluster/variables.tf#L18-L20) and [subnet_ids](https://github.com/hashicorp/terraform-aws-consul/blob/master/modules/consul-cluster/variables.tf#L51-L55). The root example sets these to the [default VPC & subnets](https://github.com/hashicorp/terraform-aws-consul/blob/master/main.tf#L153-L159) but you can easily update this for your own use case!

**Comment by andrewmeissner** [comment]
Thanks!  I'll take a stab at it.

**Comment by andrewmeissner** [comment]
https://github.com/hashicorp/terraform-aws-consul/pull/9

**Comment by andrewmeissner** [comment]
Thanks again!  Taken care of in https://github.com/hashicorp/terraform-aws-consul/pull/9
