### ISSUE TITLE
Using AWS snapshot creates conflicting node ids.

### ISSUE THREAD

**Issue by MatthiasScholz** [hashicorp/terraform-aws-consul#85]
# Issue Description
Consul creates during its operation temporary data which is stored, in the default configuration, in the folder `/opt/consul/data`. The folder contains the unique id consul generates to identify the node.

When the AWS snapshot functionality is used to start up new instances, in maybe an autoscaling group, the persistent node id is reused on the new instance and hence creates conflicts.

# Suggested Solution
Since the `run-consul` script is executed only one time after the instance was created at startup this script could be used to cleanup the `data` directory.

I would provide a PR if this is an acceptable solution.

**Comment by josh-padnick** [comment]
I'm guessing your goal is to backup the server state and you're using EBS Snapshots as a way to do that? If so, my recommendation is that you use the `consul snapshot save` command as outlined in the [Consul docs](https://www.consul.io/docs/commands/snapshot.html). This will guarantee a consistent snapshot of a given server and output a file you can upload to S3. For restores, you can download the file from S3 and run `consul snapshot restore`.

**Comment by MatthiasScholz** [comment]
I have a different kind of usage in mind.

Snapshots can be used as a source for AWS autoscaling group launch
configuration. It means one can spin up new instances based on snapshots.
Furthermore snapshots can be used as a source for packer to generate new
AMIs.

Josh Padnick <notifications@github.com> schrieb am Di., 18. Sep. 2018,
21:16:

**Comment by josh-padnick** [comment]
Hm, if you're creating AMIs for the purpose of launching Consul, I'd strongly recommend you build an AMI using Packer and our [consul-ami template](https://github.com/hashicorp/terraform-aws-consul/tree/master/examples/consul-ami). Any source used by Packer should be a clean, well-defined AMI such as Ubuntu 16.04 LTS.

If you use snapshots to build AMIs, you have no idea what kind of configuration you're actually running.

**Comment by MatthiasScholz** [comment]
It seems I was not clear in my description.

It is not about building an AMI. For this I already use the provided
template.
But about a cleanup step in the "run-consul" script.

AWS instances which should run as consul server or agents can be started
using AMIs or snapshots. Starting from a snapshot can lead to multiple
instances with the same node id. This will lead to a broker cluster.

My suggestion is to support a cleanup step in the "run-consul" script.

Josh Padnick <notifications@github.com> schrieb am Do., 20. Sep. 2018,
00:55:

**Comment by brikis98** [comment]
What's the use case for starting a consul server from a snapshot rather than an AMI if you already have an AMI?

**Comment by MatthiasScholz** [comment]
The use case is to use snapshot in the AWS launch configuration for autoscaling groups.

It might break the paradigm of immutable infrastructure, it depends on how the snapshots are used, but people might see the need to make use of the functionality provided by AWS and then spend unnecessary time in digging down the error.

If this AWS functionality is not intended to be supported by the module then at least it should be documented.

**Comment by brikis98** [comment]
I suspect you'll run into a number of issues trying to deploy auto scaling groups (ASGs) that way. Examples:

1. Each instance configures itself during boot, not only with a unique ID, but also the IPs it will advertise to the outside world, the data center its in, environment variables, etc. 
1. Each instance writes log files to disk.
1. Each instance may persist other data to disk (e.g., the state of the DB).

If you take a snapshot of such an instance and launch a new instance with it, all of this data comes along for the ride. A lot of it will be confusing at best (why do the logs and configs have this other IP in them?) and in all likelihood cause all sorts of errors (this node and its data is already part of the cluster, I can't join again).

If you already built an AMI using the code in this repo, you should use that AMI in your ASG, not a snapshot.

**Comment by MatthiasScholz** [comment]
I can understand that you do not want to support users shouting them selves in the foot.

Is there a way to improve the documentation regarding these aspects?
Since it is a valid option on how to use AWS, other users might come up with the same issue.

**Comment by brikis98** [comment]
Sure, that would be great! Perhaps the [consul-cluster module README](https://github.com/hashicorp/terraform-aws-consul/blob/master/modules/consul-cluster/README.md) is a good place to talk about the AMI you should use in the cluster and possible gotchas?

**Comment by MatthiasScholz** [comment]
Sounds good I will provide a PR adding a new section with giving some details about generated data and the antipattern.
