### ISSUE TITLE
enhancement request: amazon linux 2 support

### ISSUE THREAD

**Issue by eedwards-sk** [hashicorp/terraform-aws-consul#86]
[amazon linux 2](https://aws.amazon.com/amazon-linux-2/) has a suite of numerous updates and improvements

however, with the bump in centos it's based on, it now uses systemd instead of supervisord, so I suspect the install script will need testing and additional environment checks to use the appropriate installation method

**Comment by brikis98** [comment]
Agreed. I think at this point, systemd is available as a process supervisor by default on most major distros (Ubuntu, Amazon Linux, CentOS), so we should probably move that that. PRs for that are very welcome.
