### ISSUE TITLE
Inbound required arguments.

### ISSUE THREAD

**Issue by jarrettj** [hashicorp/terraform-aws-consul#87]
Hi,

Good day.

I'm using the consul_cluster module. Quick question, why is allowed_inbound_cidr_blocks required? If my cluster is deployed in a private subnet, would allowed_inbound_cidr_blocks be needed? If we only allowing access from a bastion instance, only allowed_inbound_security_group_ids would be needed. 

Maybe have one of allowed_inbound_cidr_blocks or allowed_inbound_security_group_ids required? I might also be completely wrong and missed something? :)

Regards.
JJ

**Comment by Etiene** [comment]
To be honest, I also don't see any reason for it to be required, so I guess we could update that (PRs welcome as well). For the moment passing an empty list would be ok :)

**Comment by jarrettj** [comment]
No worries. I’ll just that. Thanks.
